# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5c3e1ce
_src_path: git+https://github.com/fmi-faim/ipa-project-template
author: Tim-Oliver Buchholz
organization: Friedrich Miescher Institute for Biomedical Research
project_name: Demo Project
